version: '1.1'
stages:
  - build
  - security scans
  - stages 
  - production
steps:
  BuildMicroServices:
    type: parallel
    stage: build
    steps:
      BuildingNodeJSApp:
        title: Building Node JS App Image
        type: build
        image_name: orielbelzer/nodesampleapp
        working_directory: ./
        tag: '${{CF_BRANCH_TAG_NORMALIZED}}'
        dockerfile: Dockerfile
      BuildinguserAPIImage:
        title: Building User API Image
        type: build
        image_name: orielbelzer/microserviceappexample_usersapi
        working_directory: ./
        tag: '${{CF_BRANCH_TAG_NORMALIZED}}'
        dockerfile: Dockerfile
      BuildingFronEndImage:
        title: Building Front End Image
        type: build
        image_name: orielbelzer/microserviceappexample_frontend
        working_directory: ./
        tag: '${{CF_BRANCH_TAG_NORMALIZED}}'
        dockerfile: Dockerfile
      
      
        